# frozen_string_literal: true

# THIS CLASS WAS NOT AUTOGENERATED.

require 'cgi'

module PayPalCheckoutSdk
  module Webhooks
    #
    # Verifies a webhook signature.
    #
    class WebhookVerifySignatureRequest
      attr_accessor :path, :body, :headers, :verb

      def initialize()
        @headers = {}
        @body = nil
        @verb = "POST"
        @path = "/v1/notifications/verify-webhook-signature?"
        @headers["Content-Type"] = "application/json"
      end

      def request_body(verifyWebhookSignature)
        @body = verifyWebhookSignature
      end
    end
  end
end
