# frozen_string_literal: true

# THIS CLASS WAS NOT AUTOGENERATED.

require 'cgi'

module PayPalCheckoutSdk
  module Identity
    #
    # Gets a users information.
    #
    class UserinfoRequest

      attr_accessor :path, :body, :headers, :verb

      def initialize
        @headers = {}
        @body = nil
        @verb = 'GET'
        @path = '/v1/identity/oauth2/userinfo?'
        @headers['Content-Type'] = 'application/json'
      end

      def prefer(prefer)
        @headers['Prefer'] = prefer
      end

      def request_body(body)
        @body = body
      end

    end
  end
end